M48
; DRILL file {KiCad (6.0.4-0)} date Tuesday, May 03, 2022 at 09:37:04 PM
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2022-05-03T21:37:04-04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.4-0)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.800
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.200
%
G90
G05
T1
X107.62Y-91.78
T2
X83.6Y-59.6
X83.6Y-89.4
X166.4Y-59.6
X166.4Y-89.4
T0
M30
